- The Internet Engineering Task Force, BagIt Specification (last updated January 26, 2016): https://tools.ietf.org/html/draft-kunze-bagit-13
- DURASPACE, BagIt Specification: https://wiki.duraspace.org/display/DPNC/BagIt+Specification
